name: "test"
on: [pull_request]

jobs:
  rust-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Run Rust tests
        working-directory: src-tauri
        run: cargo test --locked
